### ISSUE TITLE
Interested in joining forces?

### ISSUE THREAD

**Issue by scotttrinh** [ngortheone/org-rs#1]
I've been working slowly on a similar project to write an org-mode parser in Rust and have been talking with @scarab5q about what we would want to do to get this project off the ground when he stumbled across this repo. What serendipity, right?

We made a Github org called org-rs and would be happy to house this repo there. I'd love to help with anything that feels unfinished in your current implementation. I _am_ interested in writing a more idiomatic Rust version of the parser alongside your reimplementation of the elisp version, but think what you have here is a huge leap forward towards my actual interest in writing multi-platform applications on top of org. Having this implementation would be helpful anyway, as it presents a stable public-facing API that our implementation could be compatible with and have a baseline to benchmark any improvements in speed or size that our current work might offer.

If you're interested, let me know, and I'll rename org-rs/org-rs and fork this repo to the org-rs org and make you an admin on that org. Otherwise, to reduce confusion, I might just rename our separate project. Either way, I'm excited to have been shown this work. I look forward to helping and collaborating on this! Thanks for all of the hard work you've put into this thus far!

**Comment by ngortheone** [comment]
@scotttrinh 
I am definitely interested in joining forces. I feel that this is a battle that you can't win alone.
And I am open to a repo/crate name change as well. Before going public I used "zorg-mode" name, but then I discovered that there is already a repo with  such name. Inventing names is not my strength so if you have something better than "org-rs" on your mind I am open to discuss.

>If you're interested, let me know, and I'll rename org-rs/org-rs and fork this repo to the org-rs org and make you an admin on that org.

Definitely interested! I will make this repo archived after you do this.

**Comment by mlinksva** [comment]
Just FWIW another option after renaming org-rs/org-rs and making @ngortheone an org-rs admin would be to transfer this repo to org-rs. That way watchers etc are transferred, http redirects happen, and there's no repo to archive. See https://help.github.com/en/articles/transferring-a-repository

**Comment by petr-tik** [comment]
@scotttrinh @ngortheone 

Thanks for the awesome project. This is a great initiative. I would like to suggest that you make wasm a first-class target. Compiling the library to wasm will enable other people to write web applications or embed it in other wasm runtimes currently picking up steam. Giving web developers an easy interface to work with will help us spread the magic of org mode. 

I will be happy to help with that.

It's also in my personal interest. I have a private repo generating org files from a given template. My project currently transforms a hand-written org file with jinja-like syntax mixed into the org file. Being able to template and serialise a specific version of an org tree would be a huge problem-solver.

**Comment by ngortheone** [comment]
@mlinksva I agree, transferring is a better option

**Comment by scarab5q** [comment]
Yeah maybe the name should be something a bit different to org-rs. I think that name doesn't quite do this project justice. Maybe something like:

org-io, 
orgio,
one-org,
worg,  

or if wasm is to be a first class target then potentially more cheekily:
orgwasm,
orgwasmic,
Org-asm
.... (Sorry I just thought of this and couldn't help myself)

It might seem like a small thing but I think a name that kind says that this isn't just some kind of extension to org, an add on to remacs or anything else like that. Given that this would allow for orgmode to transcend Emacs and become a fully fledged thing all of it's own. 

Sorry for the ramble but thought I would throw in my two cents.

**Comment by scarab5q** [comment]
Oh yeah completely forgot to mention that I would be ultra excited to get involved as was inferred by @scotttrinh. Though won't be able to get properly involved until June as this is my final semester of uni and have exams and stuff

**Comment by scarab5q** [comment]
Just checked all of those names I suggested before and of those the ones that are available are:

org-io, orgio, org.io, one-org, orgwasm, orgwasmic

The rest were taken

**Comment by scotttrinh** [comment]
Invited @ngortheone as an owner to the org-rs organization. Feel free to do the transfer whenever you get a chance! Renamed my WIP nom parser to `org-nom` for now.

My personal feeling about naming is that we stick with org-rs for simplicity and to make it clear what the library does: parse and serialize org expressions. If there are other tools, applications, etc. that are built on top of org-rs, that seems like a good time and place to give those projects a new name.

🎉

**Comment by ngortheone** [comment]
By the power given me by gods I rename this repo to org-io and move it to org-rs organization

**Comment by ngortheone** [comment]
@scotttrinh it is not too late to rename it back to org-rs. I personally have no preference between the two

**Comment by scarab5q** [comment]
yeah it is just a small thing I was just kind of excitedly thinking out loud sorry

**Comment by ngortheone** [comment]
@scotttrinh @scarab5q should we establish some sort of IRC or gitter?

**Comment by scarab5q** [comment]
yeah probably a good idea

**Comment by scotttrinh** [comment]
I've had good luck with gitter in the past, feel free to set one up!

**Comment by scarab5q** [comment]
~~sure Ill set one up now if you want could you add me to org-rs ?~~ sorry it seems you already had and I hadn't noticed !

**Comment by scotttrinh** [comment]
@petr-tik 

> Thanks for the awesome project. This is a great initiative. I would like to suggest that you make wasm a first-class target. Compiling the library to wasm will enable other people to write web applications or embed it in other wasm runtimes currently picking up steam. Giving web developers an easy interface to work with will help us spread the magic of org mode.

This is also my primary use-case for an org parser: make it easier to write multi-platform applications that use org as a first-class, compliant structure at the application-level. I'm primarily a web developer, so you can bet that my interest is in wasm compilation, but definitely thinking more broadly about desktop and mobile as well!

**Comment by scarab5q** [comment]
Tried to make one for org-rs but for some reason, gitter isn't recognizing it. I've made a temporary room for now until we can get gitter/hex chat set up for org-rs propperly. Here is the link ! https://gitter.im/scarab5q/org-rs

**Comment by scotttrinh** [comment]
Made an org-level gitter here: https://gitter.im/org-rs/community
