### ISSUE TITLE
syntax highlighting

### ISSUE THREAD

**Issue by ghost** [ngortheone/org-rs#17]
it seems this is not currently supported - ruby version does support it:

~~~
$ cat hello.org
#+BEGIN_SRC rust
fn main() {
   println!("alpha beta");
}
#+END_SRC

$ org-ruby hello.org
<pre class="src" lang="rust">
fn main() {
   println!(&quot;alpha beta&quot;);
}
</pre>
~~~

- https://github.com/wallyqs/org-ruby
- https://orgmode.org/manual/Working-with-source-code.html

**Comment by ngortheone** [comment]
@cup please hold off creating issues about all the things that you do not find here.
org-rs is a **parser** crate, highlighting syntax is not its job. The only 2 things that are in scope are generating parse tree and serializing it back.

Secondly, org-ruby is a presentation parser used by github for showing org documents in web ui the same way markdown is shown. It is not a fully featured org parser so comparing it org-rs is a bit strange

Third, exporting to HTML is also out of scope of this crate. It is a job of a tool that will use Parse Tree generated by this parser.

And lastly org-rs It is still in **early** development phase, the issues you open are premature. Check out [contribution guide](CONTRIBUTING.org) if you want  more details about current status.

**Comment by ngortheone** [comment]
Please refer to [FAQ](https://github.com/org-rs/org-rs/wiki/FAQ)
