### ISSUE TITLE
restriction not found

### ISSUE THREAD

**Issue by dineshadepu** [ngortheone/org-rs#2]
Hi,

I am trying to understand. I tried running tests. I get the following error,

```
    
error[E0425]: cannot find value `restriction` in this scope
   --> element/src/parser.rs:186:29
    |
186 |                             restriction, //FIXME pass `can_contain` func of current element
    |                             ^^^^^^^^^^^ not found in this scope

```
Is there any workaround to make this work for now?

**Comment by ngortheone** [comment]
I am working on this as we speak. 
Here is the corresponding place in elisp
https://code.orgmode.org/bzg/org-mode/src/master/lisp/org-element.el#L4404

The idea is to pass in `can_contain` method of the current element, not sure if I succeed though.
Stay tuned.

**Comment by dineshadepu** [comment]
Thanks for the quick reply. i am a beginner in rust. I am trying to contribute. This looks interesting to me as I use org mode heavily as a user. 

Can you create some simple issues so that I can work on them? This will help me to focus on some specific stuff and contribute in future.

**Comment by ngortheone** [comment]
This is also my first Rust project! I've been working on in privately for some time and today I made it public. Some things were in broken state when I did it. As soon as I stabilize things and make tests runnable I will create issues. Meanwhile check out contribution guide to get the idea what the current state is.

**Comment by ngortheone** [comment]
@dineshadepu I have patched things crudely, but should be enough for you to start playing with the code!

**Comment by xxzozaxx** [comment]
@dineshadepu hey bro. I would recommend you to join us at gitter chat, I'm a beginner like you or even more than you. and they talk about intersting stuff and share valuable resourcese
