### ISSUE TITLE
Description List

### ISSUE THREAD

**Issue by ghost** [ngortheone/org-rs#5]
if you put this markdown:

~~~
one two
: three four five six
~~~

it gives you a Description List with kramdown:

~~~html
<dl>
  <dt>one two</dt>
  <dd>three four five six</dd>
</dl>
~~~

https://kramdown.gettalong.org/syntax#definition-lists

however Org-mode does not appear to support Description Lists currently.
references:

https://developer.mozilla.org/Web/HTML/Element/dl

**Comment by cup** [comment]
https://github.com/wallyqs/org-ruby/issues/63

**Comment by ngortheone** [comment]
@cup 
Sorry, I did not get the gist of your statement. Care to elaborate?

**Comment by ghost** [comment]
I would like the ability to create Description Lists with Org-Rs

currently is seems this must be done with HTML rather than Org markup

**Comment by ngortheone** [comment]
If original org-mode implementation does not support this feature then org-rs will not have it too in any foreseeable future. I am sorry but planning or promising new features now is just premature. 
Secondly planning features that are not supported with Emacs' org-mode would mean creating a competing standard and I do not want to do that.

**Comment by cup** [comment]
@ngortheone thank you for clarifying - i will seek other markup projects

**Comment by sondr3** [comment]
Not sure what sources you attempted to figure this out with @cup, but org-mode very much has description lists, googling it returns a whole bunch of results, most prominent of which is [this](https://orgmode.org/guide/Plain-lists.html).

**Comment by ngortheone** [comment]
Sorry for possible misunderstanding. I do not have all possible org features in my head. But the framework I use to answer any question of this kind is simple: If it is supported by original org-mode then it will be supported in org-rs.

**Comment by sondr3** [comment]
Yeah, my answer was mostly directed at OP, not you. I completely understand keeping the entirety of org-mode in your head is impossible :smiley:

**Comment by ngortheone** [comment]
Add to #7

**Comment by ghost** [comment]
@sondr3 yes you are right!

~~~
$ cat alpha.org
- beta :: gamma
- delta :: epsilon

$ org-ruby alpha.org
<dl>
  <dt>beta</dt><dd>gamma</dd>
  <dt>delta</dt><dd>epsilon</dd>
</dl>
~~~

i was looking in the manual:

https://orgmode.org/manual

instead of the guide:

https://orgmode.org/guide

thanks for the help! likely this issue is fixed, but i will keep open as im not
sure yet how to actually test with the rust version.

**Comment by cup** [comment]
https://github.com/org-rs/org-rs/issues/16

**Comment by ngortheone** [comment]
Please refer to [FAQ](https://github.com/org-rs/org-rs/wiki/FAQ)
